name: "Continuous Integration"

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          php-version: ${{ matrix.php }}
      - name: install dependencies
        uses: ramsey/composer-install@v3
      - name: check coding standards
        run: vendor/bin/phpcs
      - name: run static analysis
        run: vendor/bin/phpstan
      - name: run benchmark
        run: vendor/bin/phpbench run --report=compressed || true
      - name: run unit tests
        run: vendor/bin/phpunit --colors=always --coverage-clover=coverage.xml || true
